-- FUNÇÕES

CREATE OR ALTER FUNCTION FN_DOBRO(@NUMERO INT)
RETURNS DECIMAL(10, 2)
AS
BEGIN
	RETURN @NUMERO*2
END
GO

SELECT DBO.FN_DOBRO(10) AS RESULTADO;

SELECT F.Pnome, F.Unome, F.Salario AS 'S.ATUAL',
	DBO.FN_DOBRO(F.Salario) AS 'DOBRO'
FROM FUNCIONARIO AS F;
GO

CREATE OR ALTER FUNCTION DBO.FN_IDADE(@DATANASC DATE)
RETURNS INT
AS
BEGIN
	RETURN DATEDIFF(YEAR, @DATANASC, CAST(GETDATE() AS DATE))
		- CASE WHEN FORMAT(@DATANASC, 'MMdd') > FORMAT(GETDATE(), 'MMdd') THEN 1 ELSE 0 END;
END;
GO
SELECT F.Pnome,
	   F.Unome,
	   F.Datanasc AS 'DATA DE NASCIMENTO',
	   DBO.FN_IDADE(F.Datanasc) AS 'IDADE'
FROM FUNCIONARIO AS F
GO
-- EXEMPLO PROFESSOR
CREATE FUNCTION FN_CALC_IDADE(@DATA DATE)
RETURNS INT
AS
BEGIN
	DECLARE @IDADE INT;
	SET @IDADE = DATEDIFF(YEAR, @DATA, GETDATE());

	IF
		(MONTH(@DATA) > MONTH(GETDATE())
		OR (MONTH(@DATA) = MONTH(GETDATE())
		AND DAY(@DATA) > DAY(GETDATE())))
	SET @IDADE = @IDADE -1;
	RETURN @IDADE;
END
GO
SELECT F.Pnome,
	   F.Unome,
	   F.Datanasc AS 'DATA DE NASCIMENTO',
	   DBO.FN_CALC_IDADE(F.Datanasc) AS 'IDADE'
FROM FUNCIONARIO AS F
GO

CREATE FUNCTION FN_FUNCIONARIOS(@NOMES VARCHAR(30))
RETURNS TABLE
AS
	RETURN(
		SELECT 
			F.Pnome,
			F.Unome
		FROM FUNCIONARIO AS F
		INNER JOIN DEPARTAMENTO AS D ON F.Dnr = D.Dnumero
		WHERE D.Dnome = @NOMES
	);
GO

SELECT *
FROM FN_FUNCIONARIOS('PESQUISA')
GO

CREATE OR ALTER FUNCTION FN_CALC_ANUAL()
RETURNS TABLE
AS
RETURN
	(
		SELECT 
			ISNULL(F.Pnome, '') + ' ' + ISNULL(F.Unome, '') AS NOME_COMPLETO,
			CAST(
			(Salario*12) + Salario + (Salario*0.3)
			 AS DECIMAL(10,2)
			 ) AS SALARIO_ANUAL_TOTAL
		FROM FUNCIONARIO AS F
	);

SELECT * FROM DBO.FN_CALC_ANUAL()
GO

CREATE FUNCTION FN_CALC_BONUS(@SALARIO DECIMAL(10, 2), @BONUS DECIMAL(7, 2))
RETURNS DECIMAL(10, 2)
AS
BEGIN
	DECLARE @SAL_ANUAL DECIMAL(10, 2);
	SET @SAL_ANUAL = (@SALARIO*12)*(1+@BONUS/100)
	RETURN @SAL_ANUAL;
END
GO

	SELECT 
		Pnome,
		Unome,
		Salario,
		DBO.FN_CALC_BONUS(Salario, 10) AS 'SALARIO + BONIFICAÇÃO' 
	FROM FUNCIONARIO 
