CREATE DATABASE AULA15
;
USE AULA15
;
CREATE TABLE ITENSPEDIDO (
	ID_ITEMPEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRI_PRODUTO VARCHAR(100),
    QUANTIDADE INT,
    VALOR_UNITARIO DECIMAL(7, 2)
)
;

CREATE TABLE auditoria (
	ACAO VARCHAR(30),
	DATA DATETIME
)


DELIMITER @

CREATE TRIGGER auditar_insercao
AFTER INSERT ON ITENSPEDIDO
FOR EACH ROW
BEGIN
    INSERT INTO auditoria (acao, data)
    VALUES ('Novo pedido inserido', NOW());
END @

DELIMITER ;

INSERT INTO ITENSPEDIDO (DESCRI_PRODUTO, QUANTIDADE, VALOR_UNITARIO) VALUES
('Teclado USB', 2, 79.90),
('Mouse Óptico', 5, 39.50),
('Monitor 24 Polegadas', 1, 899.99),
('Notebook Dell', 1, 3500.00),
('HD Externo 1TB', 3, 299.90),
('Pendrive 32GB', 10, 25.00),
('Cadeira Gamer', 1, 1200.00),
('Webcam HD', 4, 150.75),
('Headset Gamer', 2, 220.40),
('Fonte 500W', 2, 180.00);

SELECT * FROM auditoria;

DELIMITER $$

CREATE FUNCTION calcular_total_item(p_id INT)
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
    DECLARE total DECIMAL(10,2);

    SELECT QUANTIDADE * VALOR_UNITARIO
    INTO total
    FROM ITENSPEDIDO
    WHERE ID_ITEMPEDIDO = p_id;

    RETURN total;
END $$

DELIMITER ;

SELECT DESCRI_PRODUTO, CALCULAR_TOTAL_ITEM(ID_ITEMPEDIDO) AS TOTAL_DO_ITEM
FROM ITENSPEDIDO