CREATE DATABASE DBINVENTARIOTI
;

USE DBINVENTARIOTI
;

CREATE TABLE TAB_DOMINIO (
	ID_TABELA INT AUTO_INCREMENT PRIMARY KEY,
    COD_TABELA INT NOT NULL,
    ITEM_TABELA INT NOT NULL,
    DESCRICAO VARCHAR(200),
    SIGLA VARCHAR(8)
)
;

INSERT INTO TAB_DOMINIO (COD_TABELA, ITEM_TABELA, DESCRICAO, SIGLA)
VALUES(100, 0, 'Postos e Graduações', 'P/G'), 
      (100, 1, 'SOLDADO', 'SD'),
      (100, 2, 'CABO', 'CB'),
	  (100, 3, '3º SARGENTO', '3SGT'),
	  (100, 4, '2º SARGENTO', '2SGT'),
	  (100, 5, '1º SARGENTO', '1SGT'),
      (100, 6, 'SUB-TENENTE', 'ST'),
      (100, 7, 'ASPIRANTE', 'ASP'),
      (100, 8, '2º TENENTE', '2TEN'),
      (100, 9, '1º TENENTE', '1TEN')
;

INSERT INTO TAB_DOMINIO (COD_TABELA, ITEM_TABELA, DESCRICAO)
VALUES(101, 0, 'Sistemas Operacionais'), 
      (101, 1, 'windows 11'),
      (101, 2, 'Ubuntu')
;

INSERT INTO TAB_DOMINIO (COD_TABELA, ITEM_TABELA, DESCRICAO)
VALUES(102, 0, 'Tipo de peça'),
	  (102, 1, 'Fonte de energia'),
      (102, 2, 'Placa mãe'),
      (102, 3, 'Memória RAM'),
      (102, 4, 'Memória HD'),
      (102, 5, 'Memória SSD'),
      (102, 6, 'Placa de video')
;
-- ...

CREATE TABLE PESSOAS (
	ID_PESSOA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PESSOA VARCHAR(60) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    TIPO_PESSOA ENUM('FÍSICA','JURÍDICA') NOT NULL,    
    DT_CADASTRO DATE DEFAULT (CURRENT_DATE)	
)
;

CREATE TABLE QUADRO_EFETIVO (
	ID_QUADRO_EFETIVO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PESSOA INT NOT NULL,
    NIVEL_GRADUACAO_TAB INT DEFAULT 100,
    NIVEL_GRADUACAO_ITEM INT NOT NULL
)
;

CREATE TABLE MAQUINAS (
	ID_MAQUINA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PESSOA INT NOT NULL,
    ID_PECA_MAQUINA INT NOT NULL,
    NOME_MAQUINA VARCHAR(10) NOT NULL,
    SISTEMA_COD INT DEFAULT 101,
    SISTEMA_ITEM INT NOT NULL,
    ESPECIFICACOES TEXT
)
;

CREATE TABLE PECAS_MAQUINA (
  ID_PECA_MAQUINA INT AUTO_INCREMENT PRIMARY KEY,
  MARCA VARCHAR(50) NOT NULL,
  MODELO VARCHAR(50) NOT NULL,
  TIPO_PECA_COD INT DEFAULT 102,
  TIPO_PECA_ITEM INT NOT NULL
)
;
CREATE TABLE SECOES (
	ID_SECAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_DIVISAO INT NOT NULL,
    NOME_SECAO VARCHAR(100) NOT NULL
)
;
CREATE TABLE DIVISOES (
	ID_DIVISAO  INT AUTO_INCREMENT PRIMARY KEY,
    NOME_DIVISAO VARCHAR(50) NOT NULL
)

-- MODELO DE DADOS 
-- ENTIDADES
-- MAQUINAS
	-- ID_MAQUINA
    -- PEÇAS
-- SEÇÕES
	-- ID_SEÇÃO
    -- NOME_SEÇÃO
-- DIVISÃO
	-- ID_DIVISAO
    -- NOME_DIVISÃO
